platform :ios, '9.3'
use_frameworks!

target 'EPNaverMapClustering_Example' do
  pod 'EPNaverMapClustering', :path => '../'

  target 'EPNaverMapClustering_Tests' do
    inherit! :search_paths
    
  end
end
